<?
/** @var array $arParams */

if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true)
  die();
?>
<?$APPLICATION->IncludeComponent(
	"api:reviews", 
	".default", 
	array(
		"CACHE_TIME" => "31536000",
		"CACHE_TYPE" => "A",
		"COLOR" => "orange1",
		"DETAIL_HASH" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_ID" => $arParams["ELEMENT_ID"],
		"EMAIL_TO" => "",
		"FORM_CITY_VIEW" => "Y",
		"FORM_DELIVERY" => array(
		),
		"FORM_DISPLAY_FIELDS" => array(
			0 => "RATING",
			1 => "ADVANTAGE",
			2 => "DISADVANTAGE",
			3 => "ANNOTATION",
			4 => "GUEST_NAME",
			5 => "GUEST_PHONE",
		),
		"FORM_FORM_SUBTITLE" => "",
		"FORM_FORM_TITLE" => "Отзывы пациентов",
		"FORM_MESS_ADD_REVIEW_ERROR" => "Внимание!<br>Ошибка добавления отзыва",
		"FORM_MESS_ADD_REVIEW_EVENT_TEXT" => "<p>#USER_NAME# добавил(а) новый отзыв (оценка: #RATING#) ##ID#</p>
<p>Открыть в админке #LINK_ADMIN#</p>
<p>Открыть на сайте #LINK#</p>",
		"FORM_MESS_ADD_REVIEW_EVENT_THEME" => "Отзывы пациентов (оценка: #RATING#) ##ID#",
		"FORM_MESS_ADD_REVIEW_MODERATION" => "Спасибо!<br>Ваш отзыв отправлен на модерацию",
		"FORM_MESS_ADD_REVIEW_VIZIBLE" => "Спасибо!<br>Ваш отзыв №#ID# опубликован",
		"FORM_MESS_EULA" => "Нажимая кнопку «Отправить отзыв», я принимаю условия Пользовательского соглашения и даю своё согласие на обработку моих персональных данных, в соответствии с Федеральным законом от 27.07.2006 года №152-ФЗ «О персональных данных», на условиях и для целей, определенных Политикой конфиденциальности.",
		"FORM_MESS_EULA_CONFIRM" => "Для продолжения вы должны принять условия Пользовательского соглашения",
		"FORM_MESS_PRIVACY" => "Я согласен на обработку персональных данных",
		"FORM_MESS_PRIVACY_CONFIRM" => "Для продолжения вы должны принять соглашение на обработку персональных данных",
		"FORM_MESS_PRIVACY_LINK" => "",
		"FORM_MESS_STAR_RATING_1" => "Ужасный",
		"FORM_MESS_STAR_RATING_2" => "Плохой",
		"FORM_MESS_STAR_RATING_3" => "Обычный",
		"FORM_MESS_STAR_RATING_4" => "Хороший",
		"FORM_MESS_STAR_RATING_5" => "Отличный",
		"FORM_PREMODERATION" => "Y",
		"FORM_REQUIRED_FIELDS" => array(
			0 => "RATING",
			1 => "GUEST_NAME",
		),
		"FORM_RULES_LINK" => "https://".$_SERVER["HTTP_HOST"]."/user-agreement/",
		"FORM_RULES_TEXT" => "Правила публикации отзывов",
		"FORM_SHOP_BTN_TEXT" => "Оставить свой отзыв",
		"FORM_SHOP_TEXT" => "Отзывы пациентов",
		"FORM_USE_EULA" => "Y",
		"FORM_USE_PRIVACY" => "Y",
		"IBLOCK_ID" => $arParams["IBLOCK_ID"],
		"INCLUDE_CSS" => "Y",
		"INCLUDE_JQUERY" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_ITEMS_LIMIT" => "10",
		"LIST_MESS_ADD_UNSWER_EVENT_TEXT" => "#USER_NAME#, здравствуйте! 
К Вашему отзыву добавлен официальный ответ, для просмотра перейдите по ссылке #LINK#",
		"LIST_MESS_ADD_UNSWER_EVENT_THEME" => "Официальный ответ к вашему отзыву",
		"LIST_MESS_HELPFUL_REVIEW" => "Отзыв полезен?",
		"LIST_MESS_TRUE_BUYER" => "Проверенный покупатель",
		"LIST_SET_TITLE" => "N",
		"LIST_SHOP_NAME_REPLY" => "",
		"LIST_SHOW_THUMBS" => "Y",
		"LIST_SORT_FIELDS" => array(
		),
		"MESSAGE_404" => "",
		"PAGER_DESC_NUMBERING" => "Y",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "31536000",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_THEME" => "blue",
		"PAGER_TITLE" => "Отзывы",
		"PICTURE" => array(
		),
		"RESIZE_PICTURE" => "48x48",
		"SECTION_ID" => $arParams["SECTION_ID"],
		"SEF_MODE" => "N",
		"SET_STATUS_404" => "N",
		"SHOP_NAME" => $_SERVER["HTTP_HOST"],
		"SHOW_404" => "N",
		"STAT_MESS_CUSTOMER_RATING" => "На основе #N# оценок клиентов",
		"STAT_MESS_CUSTOMER_REVIEWS" => "Отзывы клиентов <span class=\"api-reviews-count\"></span>",
		"STAT_MESS_TOTAL_RATING" => "Рейтинг клиентов",
		"STAT_MIN_AVERAGE_RATING" => "5",
		"THEME" => "flat",
		"THUMBNAIL_HEIGHT" => "72",
		"THUMBNAIL_WIDTH" => "114",
		"UPLOAD_FILE_LIMIT" => "8",
		"UPLOAD_FILE_SIZE" => "10M",
		"UPLOAD_FILE_TYPE" => "",
		"UPLOAD_VIDEO_LIMIT" => "8",
		"URL" => $arParams["SECTION_SECTION_PAGE_URL"],
		"USE_FORM_MESS_FIELD_PLACEHOLDER" => "N",
		"USE_MESS_FIELD_NAME" => "N",
		"USE_STAT" => "Y",
		"USE_SUBSCRIBE" => "N",
		"COMPONENT_TEMPLATE" => ".default",
		"LIST_SORT_FIELD_1" => "ACTIVE_FROM",
		"LIST_SORT_ORDER_1" => "DESC",
		"LIST_SORT_FIELD_2" => "DATE_CREATE",
		"LIST_SORT_ORDER_2" => "DESC",
		"LIST_SORT_FIELD_3" => "ID",
		"LIST_SORT_ORDER_3" => "DESC",
		"VARIABLE_ALIASES" => array(
			"review_id" => "review_id",
			"user_id" => "user_id",
		)
	),
	false
);?>